name: Check Spelling
on:
  pull_request:
    branches:
     - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: Spell check files
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Spell check action
        uses: alexslemonade/spellcheck@main
        id: spell
        with:
          dictionary: .github/components/dictionary.txt

      - name: Upload spell check errors
        uses: actions/upload-artifact@v2
        with:
          name: spell_check_errors
          path: spell_check_errors.tsv

      - name: Fail if there are spelling errors
        if: steps.spell.outputs.error_count > 0
        run: |
          echo "There were ${{ steps.spell.outputs.error_count }} errors"
          exit 1

      - name: Post errors to PR if failed
        if: ${{ github.event_name == 'pull_request' }} && ${{ steps.spell.outputs.error_count }} > 0
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Spellcheck failed!**
            [Here are the errors.](${{ steps.artifact-upload-step.outputs.artifact-url }})
