name: Check Spelling
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: Spell check files
    permissions:
      pull-requests: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Spell check action
        uses: alexslemonade/spellcheck@v0.1.1
        id: spell
        with:
          dictionary: .github/components/dictionary.txt

      - name: Upload spell check errors
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: spell_check_errors
          path: spell_check_errors.tsv

      - name: Get the contents
        id: get-typos
        run: |
          {
            echo 'typos<<EOF'
            cat spell_check_errors.tsv
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Post errors to PR if failed
        if: ${{ github.event_name == 'pull_request' && steps.spell.outputs.error_count > 0 }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Spellcheck failed!**
            Errors:
            ${{ steps.get-typos.output.typos }}

      - name: Fail if there are spelling errors
        if: steps.spell.outputs.error_count > 0
        run: |
          echo "There were ${{ steps.spell.outputs.error_count }} errors"
          exit 1
